Update project-online-software-boundaries-and-limits.md
MicrosoftDocs/OfficeDocs-ProjectServer pull request #107
Opened 2021-01-06 00:19 UTC by hocull

Updating to callout that PWA doesn't support SharePoint's modern experience

2021-01-07 02:58 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-01-07 07:15 UTC, JohanFreelancer9 commented on ProjectOnline/project-online-software-boundaries-and-limits.md
> +- Project sites and the PWA site itself are only supported in SharePoint classic mode
```suggestion
- Project sites and the Project Web App site itself are only supported in SharePoint classic mode.
```

2021-01-07 07:17 UTC, JohanFreelancer9 requested changes
Copy review.

2021-01-12 03:13 UTC, scanum commented
@efrene PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-01-12 06:34 UTC, JohanFreelancer9 commented
@hocull - Please commit my changes. Thanks.

2021-01-12 06:47 UTC, JohanFreelancer9 approved these changes

2021-01-13 23:44 UTC, merged