Adding documentation about deploying Project to Dataverse instances. Cleaned up references to CDS
MicrosoftDocs/OfficeDocs-ProjectServer pull request #108
Opened 2021-01-09 01:28 UTC by BeReasonable

There is some new content related to deploying Project to Sandbox and Production Dataverse instances. There are also cleaned up references to CDS (which has been renamed Dataverse).

2021-01-09 01:31 UTC, BeReasonable commented
@efrene , is this something that you can help with?

2021-01-12 03:13 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-01-12 09:37 UTC, JohanFreelancer9 commented on ProjectWeb/deploying-project.md
> +> [!Note] This section refers to upcoming functionality. Project can only be deployed to the default Dataverse instance. It is not yet possible to deploy Project to other types of Dataverse instances
```suggestion
> [!Note]
> This section refers to upcoming functionality. Project can only be deployed to the default Dataverse instance. It is not yet possible to deploy Project to other types of Dataverse instances.
```

2021-01-12 09:38 UTC, JohanFreelancer9 commented on ProjectWeb/deploying-project.md
> +If you are looking to deploy to additional environments, you will need to create the environments, deploy project, and configure access for users.
```suggestion
If you are looking to deploy to additional environments, you will need to create the environments, deploy Project, and configure access for users.
```

2021-01-12 09:40 UTC, JohanFreelancer9 commented on ProjectWeb/deploying-project.md
> +> [!Note] This section only applies to Admins interesting in deploying Project to a non-Default environment.
```suggestion
> [!Note]
> This section only applies to Admins interested in deploying Project to a non-Default environment.
```

2021-01-12 09:41 UTC, JohanFreelancer9 commented on ProjectWeb/deploying-project.md
> +[Learn more about creating and managing environments](https://docs.microsoft.com/en-us/power-platform/admin/create-environment)
```suggestion
[Learn more about creating and managing environments](https://docs.microsoft.com/power-platform/admin/create-environment)
```

2021-01-12 09:42 UTC, JohanFreelancer9 commented on ProjectWeb/connect-to-project-for-the-web-data-through-powerbi-desktop.md
>  > [!Note]
```suggestion
> [!NOTE]
```

2021-01-12 09:45 UTC, JohanFreelancer9 commented on ProjectWeb/deploying-project.md
> +> [!Note] If the installation package isn't appearing in the list of     available packages, either the tenant doesn't have a Project license, or the environment was created with the "Enable Dynamics
```suggestion
> [!NOTE]
> If the installation package isn't appearing in the list of available packages, either the tenant doesn't have a Project license, or the environment was created with the "Enable Dynamics 365 Apps toggle" enabled. 
```

2021-01-12 09:46 UTC, JohanFreelancer9 commented on ProjectWeb/deploying-project.md
> +[Learn more about using the PPAC to deploy applications](https://docs.microsoft.com/en-us/power-platform/admin/manage-apps)
```suggestion
[Learn more about using the PPAC to deploy applications](https://docs.microsoft.com/power-platform/admin/manage-apps)
```

2021-01-12 09:48 UTC, JohanFreelancer9 commented on ProjectWeb/deploying-project.md
> +[Learn more about Dataverse environments]([https://docs.microsoft.com/power-platform/admin/environments-overview)
```suggestion
[Learn more about Dataverse environments](https://docs.microsoft.com/power-platform/admin/environments-overview)
```

2021-01-12 09:50 UTC, JohanFreelancer9 commented on ProjectWeb/deploying-project.md
> +There is no additional configuration needed to enable users to manage projects in the default environment. Users in the Default Environment only need a Project license to be able to create and manage
```suggestion
There is no additional configuration needed to enable users to manage Projects in the default environment. Users in the default environment only need a Project license to be able to create and manage Projects. 
```

2021-01-12 09:53 UTC, JohanFreelancer9 commented on ProjectWeb/deploying-project.md
> +> [!Note] Project-related roles are only available after the Project Service Core package has been deployed to the environment
```suggestion
> [!NOTE]
> Project-related roles are only available after the Project Service Core package has been deployed to the environment.
```

2021-01-12 09:57 UTC, JohanFreelancer9 commented on ProjectWeb/export-user-data-from-project-for-the-web.md
> +Project for the web data is stored in the [Dataverse](https://docs.microsoft.com/powerapps/maker/common-data-service/data-platform-intro) in Microsoft PowerApps. This article describes how you can:
```suggestion
Project for the web data is stored in [Dataverse](https://docs.microsoft.com/powerapps/maker/common-data-service/data-platform-intro) in Microsoft PowerApps. This article describes how you can:  
```

2021-01-12 09:59 UTC, JohanFreelancer9 commented on ProjectWeb/export-user-data-from-project-for-the-web.md
> +- **Find data about your users project and roadmap objects in CDS** - Use the Advanced Find feature in the Dynamics 365 Admin Center to find all the users data that is contained in Dataverse (for exa
```suggestion
- **Find data about your users project and roadmap objects in Dataverse** - Use the Advanced Find feature in the Dynamics 365 Admin Center to find all the users data that is contained in Dataverse (for example, objects related to their projects and roadmaps).
```

2021-01-12 10:03 UTC, JohanFreelancer9 commented on ProjectWeb/export-user-data-from-project-for-the-web.md
> +When looking for a specific users Project for the web data in Dynamics 365 Dataverse, it is located in these five Dynamics 365 solutions:
```suggestion
When looking for a specific user's Project for the web data in Dynamics 365 Dataverse, it is located in these five Dynamics 365 solutions:
```

2021-01-12 10:05 UTC, JohanFreelancer9 commented on ProjectWeb/export-user-data-from-project-for-the-web.md
>  After you unhide the columns in the spreadsheet, looks for the name of the project, and then look for the corresponding value in the Project column to find the Project ID for the project.
```suggestion
After you unhide the columns in the spreadsheet, look for the name of the project, and then look for the corresponding value in the Project column to find the Project ID for the project.
```

2021-01-12 10:17 UTC, JohanFreelancer9 commented on ProjectWeb/handling-data-for-project-for-the-web-and-roadmap.md
> +description: "Learn how Project for the web uses the Dataverse to store and manage data."
```suggestion
description: "Learn how Project for the web uses the Dataverse to store and manage data."
```
```suggestion
description: "Learn how Project for the web uses Dataverse to store and manage data."
```

2021-01-12 10:18 UTC, JohanFreelancer9 commented on ProjectWeb/handling-data-for-project-for-the-web-and-roadmap.md
> +Project for the web is built on the [Microsoft Power Platform](https://powerplatform.microsoft.com/). Project for the web data is stored in the [Dataverse](https://docs.microsoft.com/powerapps/maker/
```suggestion
Project for the web is built on the [Microsoft Power Platform](https://powerplatform.microsoft.com/). Project for the web data is stored in [Dataverse](https://docs.microsoft.com/powerapps/maker/common-data-service/data-platform-intro).
```

2021-01-12 10:19 UTC, JohanFreelancer9 commented on ProjectWeb/handling-data-for-project-for-the-web-and-roadmap.md
>  > [!Note]
```suggestion
> [!NOTE] 
```

2021-01-12 10:20 UTC, JohanFreelancer9 commented on ProjectWeb/handling-data-for-project-for-the-web-and-roadmap.md
> +### Project for the web and the Dataverse
```suggestion
### Project for the web and Dataverse
```

2021-01-12 10:21 UTC, JohanFreelancer9 commented on ProjectWeb/project-architecture-overview.md
>  > [!Note]
```suggestion
> [!NOTE] 
```

2021-01-12 10:28 UTC, JohanFreelancer9 commented on ProjectWeb/project-architecture-overview.md
> +Project for the web is built on the [Microsoft Power Platform](https://powerplatform.microsoft.com). The Power Platform consists of [PowerApps](https://docs.microsoft.com/powerapps/powerapps-overview
```suggestion
Project for the web is built on the [Microsoft Power Platform](https://powerplatform.microsoft.com). The Power Platform consists of [PowerApps](https://docs.microsoft.com/powerapps/powerapps-overview), [Power Automate](https://docs.microsoft.com/power-automate/getting-started), [Power BI](https://docs.microsoft.com/power-bi/fundamentals/power-bi-overview), and [Dataverse](https://docs.microsoft.com/powerapps/maker/common-data-service/data-platform-intro). Integration with the Microsoft Power Platform lets you easily leverage its components to [create custom business solutions](https://developer.microsoft.com/project/blogs/developing-applications-and-reports-using-the-new-project/) and do advanced analytics and reporting on project data.
```

2021-01-12 10:29 UTC, JohanFreelancer9 commented on ProjectWeb/project-architecture-overview.md
> +Project for the web data is saved in the Dataverse. The Dataverse is part of the Microsoft Power Platform, which Project for the web is built on.
```suggestion
Project for the web data is saved in Dataverse. Dataverse is part of the Microsoft Power Platform, which Project for the web is built on.  
```

2021-01-12 10:32 UTC, JohanFreelancer9 commented on ProjectWeb/project-for-the-web-get-started-guide-for-admins.md
> +Your Project for the web and Roadmap data is stored in the [Dataverse (formerly Common Data Service)](https://docs.microsoft.com/powerapps/maker/common-data-service/data-platform-intro).
```suggestion
Your Project for the web and Roadmap data is stored in [Dataverse (formerly Common Data Service)](https://docs.microsoft.com/powerapps/maker/common-data-service/data-platform-intro). 
```

2021-01-12 10:39 UTC, JohanFreelancer9 requested changes
Copy review.

2021-01-13 09:28 UTC, JohanFreelancer9 approved these changes

2021-01-13 19:26 UTC, merged