Update Export-user-data-in-Project-Server-2019.md
MicrosoftDocs/OfficeDocs-ProjectServer pull request #130
Opened 2021-09-30 21:16 UTC by NadinMerali

Adding documentation about an unsupported scenario

2021-10-01 01:37 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-10-01 02:25 UTC, JohanFreelancer9 commented on Project/Export-user-data-in-Project-Server-2019.md
> +> Saving the exported .mpp files back to Project Online or Project server is not supported.
```suggestion
> Saving the exported .mpp files back to Project Online or Project Server is not supported.
```

2021-10-01 02:25 UTC, JohanFreelancer9 requested changes
Copy review - @NadinMerali, kindly commit the suggested change. Many thanks.

2021-10-01 08:49 UTC, JohanFreelancer9 approved these changes

2022-10-24 05:10 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-02-17 23:31 UTC, merged