Update turn-project-for-the-web-off.md
MicrosoftDocs/OfficeDocs-ProjectServer pull request #161
Opened 2023-12-08 13:20 UTC by muralidhar-koduvande

Updating the verbatim based on recent feature releases

2023-12-09 05:28 UTC, JohanFreelancer9 commented on ProjectWeb/turn-project-for-the-web-off.md
> +> Turning Project for the web on or off in admin center applies to only default environment. Manage ‎Project‎ on other environments from ‎Power Platform admin center‎.</br>
```suggestion
> Turning Project for the web on or off in the admin center applies only to the default environment. Manage ‎Project‎ on other environments from ‎the Power Platform admin center‎.</br>
```

2023-12-09 05:29 UTC, JohanFreelancer9 commented on ProjectWeb/turn-project-for-the-web-off.md
> +> Turning Project for the web on or off in admin center applies to only default environment. Manage ‎Project‎ on other environments from ‎Power Platform admin center‎.</br>
```suggestion
> Turning Project for the web on or off in the admin center applies only to the default environment. Manage ‎Project‎ on other environments from ‎the Power Platform admin center‎.</br>
```

2023-12-09 05:29 UTC, JohanFreelancer9 commented on ProjectWeb/turn-project-for-the-web-off.md
> +> Turning Project for the web on or off in admin center applies to only default environment. Manage ‎Project‎ on other environments from ‎Power Platform admin center‎.</br>
```suggestion
> Turning Project for the web on or off in the admin center applies only to the default environment. Manage ‎Project‎ on other environments from ‎the Power Platform admin center‎.</br>
```

2023-12-09 05:30 UTC, JohanFreelancer9 commented on ProjectWeb/turn-project-for-the-web-off.md
>  > [!Important]
```suggestion
```

2023-12-09 05:32 UTC, JohanFreelancer9 requested changes
Copy review - @muralidhar-koduvande, kindly commit the minor suggested changes. Many thanks.

2023-12-11 14:49 UTC, muralidhar-koduvande reviewed
@JohanFreelancer9 - Thank you so much for reviewing the changes. I have made relevant changes as suggested. Please review and share your feedback.
I have also raised another PR to update the bookmark at line 46

2023-12-11 14:53 UTC, muralidhar-koduvande commented
@JohanFreelancer9 - My PR to update the bookmark at line 46 is failing with errors. Can you please help in updating this line? Or point me to how I can update it please?

2023-12-11 14:58 UTC, muralidhar-koduvande commented
@JohanFreelancer9 - Thank you so much for reviewing the changes. I have made relevant changes as suggested. I have also changed the bookmark at line 46.
Please review and share your feedback.

2023-12-11 15:27 UTC, JohanFreelancer9 approved these changes

2024-04-15 20:38 UTC, mscharlo commented
Hello @muralidhar-koduvande and @JohanFreelancer9 please let me know if these changes are still something that need to be merged in and I will have a look at them. If you can let me know that would be great, as I will close this issue in one week if I don't hear from you. Happy to reopen at any time at your request though!

2024-04-16 05:42 UTC, muralidhar-koduvande commented
@mscharlo - Please merge these changes

2024-04-18 16:50 UTC, mscharlo commented
@jenzamora please tag for merging, TY!

2025-02-13 23:21 UTC, jenzamora commented
Closing per discussion with @muralidhar-koduvande as he'll create a new, more updated PR in the near future.

2025-02-13 23:21 UTC, closed without merging