Added resolution to Project Roadmap connector missing in GUI of Data Policy
MicrosoftDocs/OfficeDocs-ProjectServer pull request #86
Opened 2020-08-06 15:57 UTC by Markus-Hanisch

…Policy in Power Platform admin center

[Project Roadmap connector is missing in data policy - data groups selection list](https://github.com/MicrosoftDocs/power-platform/issues/177#issuecomment-669308964)
The DLP policy connectors list shown in the GUI is missing the "Project Roadmap" ('shared_projectroadmap') connector. 

When you try to create a Project Roadmap and sync rows in the Project Roadmap with Microsoft Project projects (classic as well as modern), the auto-generated flow in Power Automate (see [Original template](https://emea.flow.microsoft.com/en-us/galleries/public/templates/0924e1395f0146599f7d174bc830cdc8/)) fails due to the following error message:
> Configured data policies prevent activation of flows which use the 'shared_commondataservice' and 'shared_projectroadmap' connectors. Visit the Power Automate Admin Center to view applied policies for your organization.

2020-08-13 18:36 UTC, Markus-Hanisch commented
@efrene 
Could you review my commit? Have I made any mistake? Is anything missing?

2020-08-20 12:45 UTC, binaryjam commented
I had something similar with another connector,
      Add-ConnectorToBusinessDataGroup -PolicyName $policyname  -ConnectorName shared_conversionservice

This worked,   but the same command with roadmap did not, but your version using add custom connector did.

However in the DLP UI they are listed as Custom Connectors, regardless of the mechnism I used here.   I suppose that will not matter because the full path ID is used,  I assume that is what is used as the Get DLP details cmdlet only shows that ID not the shortname.

2020-08-25 03:31 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-08-25 06:27 UTC, JohanFreelancer9 commented on ProjectWeb/turn-project-for-the-web-off.md
> +4. Project Roadmap may requires the Project Roadmap connector to be added to a **[Data Policy](https://admin.powerplatform.microsoft.com/dlp)** in the Power Platform admin center.  At the moment, the
```suggestion
4. Project Roadmap may require the Project Roadmap connector to be added to a [Data Policy](https://admin.powerplatform.microsoft.com/dlp) in the Power Platform admin center. At the moment, the [Project Roadmap connector does not show up in the GUI of the Data Policy](https://github.com/MicrosoftDocs/power-platform/issues/177). 
```

2020-08-25 06:28 UTC, JohanFreelancer9 commented on ProjectWeb/turn-project-for-the-web-off.md
> +Therefore, please follow along this guidance in order to add the Project Roadmap connector to the data group **Business** in the desired **Data Policy**.
```suggestion
Therefore, please follow this guidance in order to add the Project Roadmap connector to the data group **Business** in the desired **Data Policy**.
```

2020-08-25 06:33 UTC, JohanFreelancer9 requested changes
Copy review.

2020-08-25 19:17 UTC, sayedpfe requested changes
i believe your comment is valid and useful, but i think the location is not accurate, as you have added it to title "Turn Roadmap on or off", it should be a new title

2020-08-26 19:45 UTC, Markus-Hanisch commented
@sayedpfe 
Well, to "turn on" the Project Roadmap feature, it is not enough to enable it via the Office 365 admin center.
I assume that the majority of all Office 365 tenants have set a DLP for Power Platform connectors.
And this DLP will block the Project Roadmap feature. Furthermore, the Project Roadmap connector cannot be added to a data group of the DLP DLP through the Power Platform admin center UI.
Therefore, in my opinion this PowerShell script is a necessary step to "turn on" the Project Roadmap feature, which is the reason why I decided to place the PR here.
If you have a more suitable location, kindly let me know :)

2020-09-14 09:14 UTC, sayedpfe approved these changes

2020-09-18 01:23 UTC, scanum commented
@efrene PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-10-02 17:08 UTC, efrene approved these changes

2020-10-02 17:08 UTC, merged